/**
 * Generates one Storybook story per Codex-translated page with STATIC imports
 * + named exports (valid CSF). Run after the pages exist:  node scripts/gen-stories.mjs
 */
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pagesDir = join(here, "../src/pages");

const slugs = readdirSync(pagesDir)
  .filter((f) => /^[0-9].*\.tsx$/.test(f))
  .map((f) => f.replace(/\.tsx$/, ""))
  .sort();

// Valid TS identifier: always starts with a letter (export names can't be octal).
const ident = (s) => "Page_" + s.replace(/[^a-zA-Z0-9]/g, "_");

const lines = [
  "// AUTO-GENERATED by scripts/gen-stories.mjs — do not hand-edit.",
  'import type { Meta, StoryObj } from "@storybook/react-vite";',
  'import { MemoryRouter } from "react-router-dom";',
  ...slugs.map((s, i) => `import P${i} from "./${s}.js";`),
  "",
  "const meta: Meta = { title: \"Brief Pages\", parameters: { layout: \"fullscreen\" } };",
  "export default meta;",
  "type S = StoryObj;",
  "const wrap = (C: React.ComponentType) => () => (<MemoryRouter><C /></MemoryRouter>);",
  "",
  ...slugs.map(
    (s, i) =>
      `export const ${ident(s)}: S = { name: "${s}", render: wrap(P${i} as unknown as React.ComponentType) };`,
  ),
  "",
];

writeFileSync(join(pagesDir, "pages.generated.stories.tsx"), lines.join("\n") + "\n");
console.log(`[gen-stories] wrote ${slugs.length} stories`);
