// AUTO-GENERATED by brief/style-dictionary.config.js from brief/tokens.json.
// Do not hand-edit. Run `npm run tokens` to regenerate.
/* eslint-disable */
export const tokens = {
  colors: {
  "background": "#ffffff",
  "sidebar": "#fafafa",
  "hover": "#f9fafb",
  "subtle": "#f8fafc",
  "border": "#e5e7eb",
  "border-strong": "#d1d5db",
  "border-subtle": "#f1f5f9",
  "foreground": "#0f172a",
  "secondary": "#475569",
  "muted": "#94a3b8",
  "disabled": "#cbd5e1",
  "primary": "#4f46e5",
  "primary-hover": "#4338ca",
  "primary-active": "#3730a3",
  "primary-tint": "#eef2ff",
  "primary-tint-2": "#e0e7ff",
  "success": "#16a34a",
  "success-tint": "#dcfce7",
  "warning": "#d97706",
  "warning-tint": "#fef3c7",
  "danger": "#dc2626",
  "danger-tint": "#fee2e2",
  "info": "#0284c7",
  "info-tint": "#e0f2fe"
},
  borderRadius: {
  "sm": "4px",
  "md": "6px",
  "lg": "8px",
  "xl": "10px"
},
  boxShadow: {
  "pop": "0 1px 2px rgba(15, 23, 42, 0.04), 0 8px 24px rgba(15, 23, 42, 0.08)",
  "card": "0 1px 0 rgba(15, 23, 42, 0.04)"
},
  fontFamily: { sans: ["Inter var","Inter","-apple-system","BlinkMacSystemFont","Segoe UI","Roboto","sans-serif"] },
} as const;

export default tokens;
