// AUTO-GENERATED by scripts/gen-stories.mjs — do not hand-edit.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { MemoryRouter } from "react-router-dom";
import P0 from "./01-signin.js";
import P1 from "./02-onboarding.js";
import P2 from "./03-dashboard.js";
import P3 from "./04-contacts.js";
import P4 from "./05-contact-detail.js";
import P5 from "./06-vendors.js";
import P6 from "./07-vendor-detail.js";
import P7 from "./08-projects-board.js";
import P8 from "./09-project-detail.js";
import P9 from "./10-pipelines.js";
import P10 from "./11-calendar.js";
import P11 from "./12-conversations.js";
import P12 from "./13-workflows.js";
import P13 from "./14-forms.js";
import P14 from "./15-settings.js";
import P15 from "./16-spec-sheet.js";

const meta: Meta = { title: "Brief Pages", parameters: { layout: "fullscreen" } };
export default meta;
type S = StoryObj;
const wrap = (C: React.ComponentType) => () => (<MemoryRouter><C /></MemoryRouter>);

export const Page_01_signin: S = { name: "01-signin", render: wrap(P0 as unknown as React.ComponentType) };
export const Page_02_onboarding: S = { name: "02-onboarding", render: wrap(P1 as unknown as React.ComponentType) };
export const Page_03_dashboard: S = { name: "03-dashboard", render: wrap(P2 as unknown as React.ComponentType) };
export const Page_04_contacts: S = { name: "04-contacts", render: wrap(P3 as unknown as React.ComponentType) };
export const Page_05_contact_detail: S = { name: "05-contact-detail", render: wrap(P4 as unknown as React.ComponentType) };
export const Page_06_vendors: S = { name: "06-vendors", render: wrap(P5 as unknown as React.ComponentType) };
export const Page_07_vendor_detail: S = { name: "07-vendor-detail", render: wrap(P6 as unknown as React.ComponentType) };
export const Page_08_projects_board: S = { name: "08-projects-board", render: wrap(P7 as unknown as React.ComponentType) };
export const Page_09_project_detail: S = { name: "09-project-detail", render: wrap(P8 as unknown as React.ComponentType) };
export const Page_10_pipelines: S = { name: "10-pipelines", render: wrap(P9 as unknown as React.ComponentType) };
export const Page_11_calendar: S = { name: "11-calendar", render: wrap(P10 as unknown as React.ComponentType) };
export const Page_12_conversations: S = { name: "12-conversations", render: wrap(P11 as unknown as React.ComponentType) };
export const Page_13_workflows: S = { name: "13-workflows", render: wrap(P12 as unknown as React.ComponentType) };
export const Page_14_forms: S = { name: "14-forms", render: wrap(P13 as unknown as React.ComponentType) };
export const Page_15_settings: S = { name: "15-settings", render: wrap(P14 as unknown as React.ComponentType) };
export const Page_16_spec_sheet: S = { name: "16-spec-sheet", render: wrap(P15 as unknown as React.ComponentType) };

