#!/usr/bin/env python3
"""DesignersMeet mockup generator.

Emits 15 high-fidelity HTML mockups + gallery + spec sheet.
All chrome (sidebar, topbar) is generated by this script so all screens
stay in lockstep. Each screen-specific function returns its page body only.
"""
from pathlib import Path

ROOT = Path(__file__).parent
SCREENS = ROOT / "screens"
SCREENS.mkdir(parents=True, exist_ok=True)
(ROOT / "shared").mkdir(parents=True, exist_ok=True)

# ───────────────────────── Shared chrome ──────────────────────────

NAV = [
    ("dashboard",     "Dashboard",     "layout-dashboard"),
    ("contacts",      "Contacts",      "users"),
    ("vendors",       "Vendors",       "hard-hat"),
    ("pipelines",     "Pipelines",     "git-branch"),
    ("projects",      "Projects",      "layers"),
    ("calendar",      "Calendar",      "calendar"),
    ("conversations", "Conversations", "messages-square"),
    ("forms",         "Forms",         "clipboard-list"),
    ("workflows",     "Workflows",     "zap"),
    ("reports",       "Reports",       "bar-chart-3"),
    ("settings",      "Settings",      "settings"),
]

def sidebar(active: str) -> str:
    items = []
    for key, label, icon in NAV:
        active_attr = "true" if key == active else "false"
        items.append(
            f'<div class="nav-item" data-active="{active_attr}">'
            f'<i data-lucide="{icon}"></i><span>{label}</span></div>'
        )
    nav_html = "\n          ".join(items)
    return f"""
    <aside class="w-[232px] flex-shrink-0 border-r border-[#E5E7EB] bg-[#FAFAFA] flex flex-col">
      <div class="px-4 py-3 border-b border-[#E5E7EB] flex items-center justify-between">
        <div class="dm-brand">
          <span class="dm-brand-glyph">D</span>
          <span>DesignersMeet</span>
        </div>
        <button class="btn-icon" title="Collapse"><i data-lucide="panel-left-close" class="icon-sm"></i></button>
      </div>
      <div class="px-3 pt-3">
        <div class="workspace-pill">
          <div class="flex items-center gap-2 min-w-0">
            <div class="w-6 h-6 rounded-md bg-gradient-to-br from-indigo-500 to-indigo-600 text-white text-[10px] font-bold flex items-center justify-center flex-shrink-0">HQ</div>
            <div class="min-w-0">
              <div class="text-[12px] font-semibold text-slate-900 truncate">DesignersMeet HQ</div>
              <div class="text-[10px] text-slate-500 truncate">Bengaluru workspace</div>
            </div>
          </div>
          <i data-lucide="chevrons-up-down" class="icon-sm text-slate-400"></i>
        </div>
      </div>
      <nav class="px-2 pt-3 flex-1 overflow-y-auto">
        <div class="nav-section-label">Workspace</div>
        <div class="space-y-0.5">
          {nav_html}
        </div>
        <div class="nav-section-label">Surfaces</div>
        <div class="space-y-0.5">
          <div class="nav-item" data-active="false"><i data-lucide="mail"></i><span>Outlook add-in</span></div>
          <div class="nav-item" data-active="false"><i data-lucide="users-round"></i><span>Teams app</span></div>
          <div class="nav-item" data-active="false"><i data-lucide="layout-grid"></i><span>M365 launcher</span></div>
        </div>
      </nav>
      <div class="px-3 py-3 border-t border-[#E5E7EB]">
        <div class="flex items-center gap-2 px-1">
          <div class="avatar avatar-a">MS</div>
          <div class="min-w-0">
            <div class="text-[12px] font-semibold text-slate-900 truncate">Manish</div>
            <div class="text-[10px] text-slate-500 truncate">Workspace owner</div>
          </div>
          <button class="btn-icon ml-auto" title="Menu"><i data-lucide="more-horizontal" class="icon-sm"></i></button>
        </div>
      </div>
    </aside>
    """

def topbar(crumbs: list[str] = None, right_extra: str = "") -> str:
    crumbs = crumbs or []
    crumb_html = ""
    if crumbs:
        parts = []
        for i, c in enumerate(crumbs):
            last = (i == len(crumbs) - 1)
            color = "text-slate-900 font-medium" if last else "text-slate-500"
            parts.append(f'<span class="{color}">{c}</span>')
        crumb_html = (
            '<nav class="flex items-center gap-2 text-[13px]">'
            + '<i data-lucide="chevron-right" class="icon-sm text-slate-300"></i>'.join(parts)
            + '</nav>'
        )

    return f"""
    <header class="app-topbar">
      {crumb_html}
      <div class="dm-search flex-1 max-w-[480px] ml-auto mr-auto">
        <i data-lucide="search"></i>
        <input type="text" placeholder="Search contacts, projects, vendors…" />
        <span class="absolute right-2 top-1/2 -translate-y-1/2"><kbd class="kbd">⌘K</kbd></span>
      </div>
      <div class="flex items-center gap-1 ml-auto">
        {right_extra}
        <button class="btn-icon" title="Help"><i data-lucide="circle-help" class="icon-sm"></i></button>
        <button class="btn-icon relative" title="Notifications">
          <i data-lucide="bell" class="icon-sm"></i>
          <span class="absolute top-1 right-1 w-1.5 h-1.5 rounded-full bg-indigo-600"></span>
        </button>
        <div class="w-px h-6 bg-slate-200 mx-1"></div>
        <button class="flex items-center gap-2 px-2 py-1 rounded-md hover:bg-slate-50">
          <div class="avatar avatar-a avatar-sm">MS</div>
          <i data-lucide="chevron-down" class="icon-sm text-slate-400"></i>
        </button>
      </div>
    </header>
    """

def page(title: str, active_nav: str, body: str, crumbs=None, topbar_right="", chromeless=False) -> str:
    """Wrap a screen body in the full app shell."""
    head = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=1440, initial-scale=1" />
  <title>{title} · DesignersMeet</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="../shared/styles.css" />
  <script src="https://unpkg.com/lucide@latest/dist/umd/lucide.js"></script>
</head>
<body class="bg-white text-slate-900 antialiased">
"""
    if chromeless:
        shell = body
    else:
        shell = f"""
  <div class="flex h-screen overflow-hidden">
    {sidebar(active_nav)}
    <div class="flex-1 flex flex-col overflow-hidden min-w-0">
      {topbar(crumbs, topbar_right)}
      <main class="flex-1 overflow-auto bg-white">
        {body}
      </main>
    </div>
  </div>
"""
    return head + shell + """
  <script>if (window.lucide) lucide.createIcons();</script>
</body>
</html>
"""

# ───────────────────────── Helpers ──────────────────────────

def avatar(initials: str, variant: str = "a", size: str = "") -> str:
    cls = f"avatar avatar-{variant}"
    if size: cls += f" avatar-{size}"
    return f'<div class="{cls}">{initials}</div>'


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


# ────────────────────── Screen builders ──────────────────────

from screen_builders import (
    s01_signin, s02_onboarding, s03_dashboard,
    s04_contacts_list, s05_contact_detail,
    s06_vendors_list, s07_vendor_detail,
    s08_projects_board, s09_project_detail,
    s10_pipelines, s11_calendar, s12_conversations,
    s13_workflows, s14_forms, s15_settings,
    s16_spec_sheet, gallery_body,
)

SCREEN_DEFS = [
    ("01-signin.html",        "Sign in",            "",              s01_signin,        [],                                              True),
    ("02-onboarding.html",    "Onboarding",         "dashboard",     s02_onboarding,    ["Welcome"],                                     False),
    ("03-dashboard.html",     "Dashboard",          "dashboard",     s03_dashboard,     ["Dashboard"],                                   False),
    ("04-contacts.html",      "Contacts",           "contacts",      s04_contacts_list, ["Contacts", "All contacts"],                    False),
    ("05-contact-detail.html","Contact detail",     "contacts",      s05_contact_detail,["Contacts", "Clients", "Priya Raghavan"],      False),
    ("06-vendors.html",       "Vendors",            "vendors",       s06_vendors_list,  ["Vendors", "All vendors"],                      False),
    ("07-vendor-detail.html", "Vendor detail",      "vendors",       s07_vendor_detail, ["Vendors", "Aurora Studio"],                    False),
    ("08-projects-board.html","Projects board",     "projects",      s08_projects_board,["Projects", "Board"],                           False),
    ("09-project-detail.html","Project detail",     "projects",      s09_project_detail,["Projects", "Brand Refresh — Lumen Café"],     False),
    ("10-pipelines.html",     "Pipelines",          "pipelines",     s10_pipelines,     ["Pipelines", "Sales"],                          False),
    ("11-calendar.html",      "Calendar",           "calendar",      s11_calendar,      ["Calendar", "This week"],                       False),
    ("12-conversations.html", "Conversations",      "conversations", s12_conversations, ["Conversations", "Unified inbox"],              False),
    ("13-workflows.html",     "Workflows",          "workflows",     s13_workflows,     ["Workflows", "Vendor onboarding sequence"],    False),
    ("14-forms.html",         "Forms",              "forms",         s14_forms,         ["Forms", "Vendor onboarding form"],             False),
    ("15-settings.html",      "Settings",           "settings",      s15_settings,      ["Settings", "Integrations"],                    False),
    ("16-spec-sheet.html",    "Spec sheet",         "",              s16_spec_sheet,    [],                                              True),
]

def main():
    print("Building DesignersMeet mockups…")
    for filename, title, active, builder, crumbs, chromeless in SCREEN_DEFS:
        body = builder()
        html = page(title, active, body, crumbs=crumbs, chromeless=chromeless)
        write(SCREENS / filename, html)

    # Index gallery
    idx_html = page("Mockup gallery", "", gallery_body(), crumbs=[], chromeless=True)
    write(ROOT / "index.html", idx_html.replace('../shared/styles.css', 'shared/styles.css'))
    print("Done.")

if __name__ == "__main__":
    main()
