/**
 * DesignersMeet Style Dictionary build.
 * Source of truth: brief/tokens.json (W3C DTCG format).
 * Generates:
 *   - packages/frontend/src/styles/tokens.css   (CSS custom properties)
 *   - packages/frontend/tailwind.tokens.ts       (Tailwind theme fragment)
 *
 * Run: node brief/style-dictionary.config.js   (from repo root)
 *
 * These two outputs are the ONLY sanctioned places hex values may appear.
 * tailwind.config.ts imports tailwind.tokens.ts — never hand-edit colors.
 */
import StyleDictionary from "style-dictionary";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const TOKENS = resolve(here, "tokens.json");

/** Emit a Tailwind theme fragment as a typed TS module. */
StyleDictionary.registerFormat({
  name: "javascript/tailwind-tokens",
  format: ({ dictionary }) => {
    const colors = {};
    const borderRadius = {};
    const boxShadow = {};
    let fontSans = [];

    for (const t of dictionary.allTokens) {
      const [group, name] = t.path;
      const v = t.$value ?? t.value;
      if (group === "color") colors[name] = v;
      else if (group === "radius") borderRadius[name] = v;
      else if (group === "shadow") boxShadow[name] = v;
      else if (group === "font" && name === "sans") {
        fontSans = String(v)
          .split(",")
          .map((s) => s.trim().replace(/^'(.*)'$/, "$1"));
      }
    }

    return (
      "// AUTO-GENERATED by brief/style-dictionary.config.js from brief/tokens.json.\n" +
      "// Do not hand-edit. Run `npm run tokens` to regenerate.\n" +
      "/* eslint-disable */\n" +
      "export const tokens = {\n" +
      `  colors: ${JSON.stringify(colors, null, 2)},\n` +
      `  borderRadius: ${JSON.stringify(borderRadius, null, 2)},\n` +
      `  boxShadow: ${JSON.stringify(boxShadow, null, 2)},\n` +
      `  fontFamily: { sans: ${JSON.stringify(fontSans)} },\n` +
      "} as const;\n\n" +
      "export default tokens;\n"
    );
  },
});

const sd = new StyleDictionary({
  source: [TOKENS],
  usesDtcg: true,
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: resolve(repoRoot, "packages/frontend/src/styles/") + "/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: { outputReferences: false, selector: ":root" },
        },
      ],
    },
    tailwind: {
      transformGroup: "js",
      buildPath: resolve(repoRoot, "packages/frontend/") + "/",
      files: [{ destination: "tailwind.tokens.ts", format: "javascript/tailwind-tokens" }],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
console.log("[style-dictionary] tokens.css + tailwind.tokens.ts generated.");
